# Generated by Django 3.2.8 on 2021-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description_short', models.CharField(max_length=512)),
                ('description_long', models.TextField()),
                ('lng', models.CharField(max_length=17)),
                ('lat', models.CharField(max_length=17)),
            ],
        ),
    ]
