# Generated by Django 3.2.8 on 2021-10-31 15:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(default='default text', verbose_name='Детальное писание Temp'),
            preserve_default=False,
        ),
    ]
