# Generated by Django 3.2.8 on 2021-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
