# Generated by Django 3.2.9 on 2021-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20211103_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Краткое описание'),
        ),
    ]
