# Generated by Django 3.2.9 on 2021-11-07 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20211106_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Географические координаты должны быть в формате: '55.1234567' или '-134.1234567'.", regex='^-?[1]?\\d{1,2}\\.\\d{0,7}$')], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Географические координаты должны быть в формате: '55.1234567' или '-134.1234567'.", regex='^-?[1]?\\d{1,2}\\.\\d{0,7}$')], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(help_text='Напишите уникальное условное обозначение локации, например "moscow-legends2021"', unique=True, verbose_name='Обозначение'),
        ),
    ]
