# Generated by Django 3.2.9 on 2021-11-11 19:48

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20211107_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-90, 'Широта должна быть в диапазоне от -90 до 90'), django.core.validators.MaxValueValidator(90, 'Широта должна быть в диапазоне от -90 до 90')], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-180, 'Долгота должна быть в диапазоне от -180 до 180'), django.core.validators.MaxValueValidator(180, 'Долгота должна быть в диапазоне от -180 до 180')], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='', help_text='Напишите уникальное условное обозначение локации, например "moscow-legends2021"', verbose_name='Обозначение'),
        ),
    ]
