# Generated by Django 3.2.9 on 2021-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20211111_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(help_text='Напишите уникальное условное обозначение локации, например "moscow-legends2021"', unique=True, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
    ]
